# Cron schedules are documented in supabase/function_schedules.json until CLI support returns.

[functions."crawl-authorities"]
verify_jwt = false

[functions."process-learning"]
verify_jwt = false

[functions."drive-watcher"]
verify_jwt = false

[functions."regulator-digest"]
verify_jwt = false

[functions."transparency-digest"]
verify_jwt = false
