version: "3.9"
services:
  supabase-db:
    image: supabase/postgres:15.1.1.105
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: supabase
    volumes:
      - supabase-data:/var/lib/postgresql/data
volumes:
  supabase-data:
